Window.SetBackgroundTopColor(0.01, 0.02, 0.05);
Window.SetBackgroundBottomColor(0.02, 0.02, 0.08);

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2);

fun refresh_callback ()
{
    logo.sprite.SetOpacity(1);
}

Plymouth.SetRefreshFunction(refresh_callback);
